# Generated by Django 6.0 on 2025-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_gram', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
